### ISSUE TITLE
knative-camel-operator.v0.18.0 camel-controller-manager CreateContainerError on current OCP 4.6 and 4.7

### ISSUE THREAD

**Issue by maschmid** [openshift-knative/knative-camel-operator#14]
Installing the current knative-camel-operator (0.18.0) from community OperatorHub fails on current OCP versions (tried on 4.6.18 , 4.7.0)

The camel-controller-manager pod gets into CreateContainerError state, with the following error

```
container create failed: time="2021-03-02T12:02:28Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```

To reproduce on OCP 4.6.18 or 4.7.0 (tested on AWS),
1.  Install Serverless Operator (current 1.13.0)
2.  Create KnativeServing in knative-serving and KnativeEventing in knative-eventing
3.  Install "Knative Apache Camel Operator" (currently 0.18.0) from the community OperatorHub
4. Notice the operator installation fails, with the camel-controller-manager pod in CreateContainerError state.

**Comment by nicolaferraro** [comment]
This is strange, I just installed it on a `4.6.15` cluster and it's working. The base image should be the "nonroot" one, so I wouldn't expect this behavior

**Comment by maschmid** [comment]
I can confirm it works on 4.6.15 ... It could be an OCP regression... possibly introduced by https://github.com/projectatomic/runc/commit/e541951c107025363752afe4fb483d3b8d71addd

**Comment by maschmid** [comment]
I have opened https://bugzilla.redhat.com/show_bug.cgi?id=1934177 , let's see if OCP sees this as a regression.

**Comment by maschmid** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1934177#c6  , it doesn't look promising. We'll probably need to workaround it by running it as an explicit runAsUser: 65532  or something...
